# Generated by Django 6.0.1 on 2026-01-22 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_brand_alter_car_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='factory_yaer',
            new_name='factory_year',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='model_yaer',
            new_name='model_year',
        ),
    ]
